import { useState } from "react";
import { Check, ChevronRight, Inbox, Link2, Mail, RefreshCw, ShieldCheck, X } from "lucide-react";
import { mails } from "../data/mock";
import { Badge, Card, PageHeader } from "../components/ui";

export default function EmailsPage() {
  const [selected, setSelected] = useState(mails[2]);
  const [resolved, setResolved] = useState<string[]>([]);
  return <div className="page page-enter"><PageHeader title="招聘邮件" description="识别招聘进展，确认匹配后安全更新岗位流程" action={<button className="button button--secondary"><RefreshCw size={16}/>立即检查</button>} />
    <div className="mail-stats"><Card><span className="stat-icon blue"><Inbox/></span><span><small>本周新邮件</small><strong>18</strong></span></Card><Card><span className="stat-icon orange"><Link2/></span><span><small>待确认匹配</small><strong>2</strong></span></Card><Card><span className="stat-icon green"><Check/></span><span><small>自动更新流程</small><strong>12</strong></span></Card><div className="privacy-note"><ShieldCheck size={18}/><span><strong>邮件内容仅在本机处理</strong><small>外部分析前会明确提示数据范围</small></span></div></div>
    <div className="email-layout"><Card className="email-list"><div className="email-filters"><button className="active">全部 <b>18</b></button><button>待确认 <b>2</b></button><button>已更新</button></div>{mails.map(mail=><button className={`email-item ${selected.id===mail.id?"selected":""}`} key={mail.id} onClick={()=>setSelected(mail)}><span className="company-logo">{mail.company[0]}</span><span><span><strong>{mail.company}</strong><time>{mail.time}</time></span><b>{mail.subject}</b><small>{mail.summary}</small><span><Badge tone={mail.status==="待确认"?"orange":"green"}>{resolved.includes(mail.id)?"已确认":mail.status}</Badge><em>{mail.confidence}% 匹配</em></span></span></button>)}</Card>
      <Card className="email-detail"><div className="detail-head"><div><Badge tone={selected.status==="待确认"?"orange":"blue"}>{selected.type}</Badge><h2>{selected.subject}</h2><p>{selected.company} 招聘团队 &lt;recruiting@company.com&gt;</p></div><button><X size={18}/></button></div><div className="mail-body"><p>林同学，您好：</p><p>{selected.summary} 我们期待与您进一步沟通，请您留意后续安排并按时参与。</p><p>感谢您对 {selected.company} 的关注。</p></div><div className="match-analysis"><div className="analysis-title"><span><Link2 size={17}/>匹配分析</span><strong>{selected.confidence}% 高置信度</strong></div><div className="match-target"><span className="company-logo">{selected.company[0]}</span><span><strong>{selected.company} · {selected.role}</strong><small>岗位编号 TL-2026-0713 · 当前阶段：已投递</small></span><ChevronRight size={18}/></div><dl><div><dt>公司名称</dt><dd>主题与正文均出现“{selected.company}”</dd></div><div><dt>岗位名称</dt><dd>与已投岗位名称高度相似</dd></div><div><dt>时间关联</dt><dd>投递后 5 天收到，符合招聘流程</dd></div></dl></div><div className="update-suggestion"><strong>建议更新</strong><p>新增“{selected.type}”时间线事件，并将岗位状态更新至“{selected.type}”。所有自动操作均可撤销。</p></div><div className="detail-actions"><button className="button button--secondary">忽略邮件</button><button className="button button--secondary">重新匹配</button><button className="button button--primary" onClick={()=>setResolved([...resolved,selected.id])}><Check size={16}/>{resolved.includes(selected.id)?"已确认匹配":"确认匹配并更新"}</button></div></Card>
    </div>
  </div>;
}
