import { BarChart3, BookOpenCheck, BrainCircuit, BriefcaseBusiness, Check, ChevronRight, CircleDollarSign, Clock3, Database, FileAudio, FileText, KeyRound, Mail, Mic2, Play, Plus, RotateCcw, Settings, ShieldCheck, Sparkles, Star, Target, Upload, UserRound } from "lucide-react";
import { Badge, Card, CardHeader, PageHeader } from "../components/ui";

type Kind = "preparation" | "mock" | "reviews" | "questions" | "offers" | "analytics" | "settings";

const meta: Record<Kind, { title: string; description: string }> = {
  preparation: { title: "面试准备", description: "把 JD、简历与历史经验整理成可执行的准备计划" },
  mock: { title: "模拟面试", description: "针对目标岗位进行结构化练习与动态追问" },
  reviews: { title: "面试复盘", description: "校正真实面试记录，沉淀问题、故事与薄弱项" },
  questions: { title: "个人题库", description: "持续积累高频问题、最佳回答与 STAR 故事" },
  offers: { title: "Offer 管理", description: "客观比较选择维度，同时保留你的最终决定权" },
  analytics: { title: "数据分析", description: "从投递转化和面试表现中找到下一步行动" },
  settings: { title: "设置", description: "管理本地数据、外部服务、隐私权限与备份" },
};

export default function FeaturePages({ kind }: { kind: Kind }) {
  const page = meta[kind];
  return <div className="page page-enter"><PageHeader title={page.title} description={page.description} action={kind!=="settings"&&kind!=="analytics"?<button className="button button--primary"><Plus size={16}/>{kind==="reviews"?"上传面试":kind==="mock"?"开始模拟":"新建内容"}</button>:undefined}/>{kind==="preparation"&&<Preparation/>}{kind==="mock"&&<MockInterview/>}{kind==="reviews"&&<Reviews/>}{kind==="questions"&&<Questions/>}{kind==="offers"&&<Offers/>}{kind==="analytics"&&<Analytics/>}{kind==="settings"&&<SettingsPage/>}</div>;
}

function Preparation(){return <><div className="prep-hero"><div><Badge tone="blue">进行中</Badge><h2>蚂蚁集团 · 后端开发工程师</h2><p>基于 JD、后端开发简历和 12 条真实面经生成</p><div className="prep-progress"><span><i style={{width:"72%"}}/></span><b>准备完成 72%</b></div></div><button className="button button--primary"><Sparkles size={16}/>更新准备方案</button></div><div className="three-grid"><Card><CardHeader title="岗位理解"/><InfoList items={[["核心职责","高并发交易系统、微服务治理"],["核心能力","Java、分布式、数据一致性"],["业务场景","支付链路与风险控制"]]}/></Card><Card><CardHeader title="简历匹配"/><div className="score-display"><strong>82</strong><span>/100<small>匹配度较高</small></span></div><InfoList items={[["高匹配","订单系统重构经历"],["需补充","缺少峰值 QPS 量化"],["风险点","项目中的个人贡献"]]}/></Card><Card><CardHeader title="准备清单" action="查看全部"/><CheckList items={["梳理订单一致性方案","准备项目性能数据","练习 3 分钟自我介绍","复习 JVM 调优"]}/></Card></div><Card className="question-preview"><CardHeader title="预测问题" action="进入题库"/><div className="question-columns">{[["简历深挖","为什么选择消息队列解耦？","项目遇到过最严重的线上问题是什么？"],["专业能力","如何保证分布式事务一致性？","说说 JVM 内存模型"],["行为面试","讲一次意见冲突的经历","你如何推动跨团队协作？"]].map(([title,...qs])=><div key={title}><Badge tone={title==="专业能力"?"green":title==="行为面试"?"purple":"blue"}>{title}</Badge>{qs.map(q=><button key={q}>{q}<ChevronRight size={15}/></button>)}</div>)}</div></Card></>}

function MockInterview(){return <div className="mock-layout"><Card className="mock-config"><CardHeader title="创建一场模拟面试" subtitle="预计 25 分钟"/><div className="form-grid"><label className="full"><span>目标岗位</span><select><option>蚂蚁集团 · 后端开发工程师</option><option>腾讯科技 · 后台开发工程师</option></select></label><label><span>面试类型</span><select><option>技术综合面试</option><option>行为面试</option><option>项目深挖</option></select></label><label><span>难度</span><select><option>贴近真实面试</option><option>基础练习</option><option>压力追问</option></select></label><label><span>问题数量</span><select><option>8 题</option><option>5 题</option><option>12 题</option></select></label><label><span>回答方式</span><select><option>语音回答</option><option>文字回答</option></select></label></div><div className="toggle-list"><span><b>动态追问</b><small>根据回答细节生成后续问题</small><i className="toggle on"/></span><span><b>每题后反馈</b><small>完成当前问题后立即查看建议</small><i className="toggle"/></span></div><button className="button button--primary large"><Play size={17}/>开始模拟面试</button></Card><div className="mock-side"><Card><CardHeader title="上次训练" action="查看记录"/><div className="last-session"><span className="stat-icon purple"><Mic2/></span><div><strong>腾讯 · 技术二面模拟</strong><small>8 道问题 · 32 分钟</small></div><b>78<span>分</span></b></div><div className="feedback"><span>逻辑结构 <b>良好</b></span><span>量化表达 <b className="warn">待加强</b></span><span>专业细节 <b>稳定</b></span></div></Card><Card><CardHeader title="本周训练"/><div className="week-goal"><strong>3 <small>/ 4 场</small></strong><div><span><i style={{width:"75%"}}/></span><p>再完成 1 场即可达成本周目标</p></div></div></Card></div></div>}

function Reviews(){return <><div className="review-upload"><div className="upload-icon"><FileAudio size={28}/></div><div><h3>导入一场真实面试</h3><p>支持 MP3、WAV、M4A、MP4、MOV 或转写文本；原始文件默认仅保存在本地</p></div><button className="button button--secondary"><Upload size={16}/>选择文件</button></div><div className="two-grid"><Card><CardHeader title="待完成复盘" action="全部记录"/><SessionList/></Card><Card><CardHeader title="持续改善"/><div className="improve-list"><span><i className="stat-icon purple"><BrainCircuit/></i><b>个人贡献不够清晰<small>最近 3 场出现 · 建议练习 STAR 行动部分</small></b><Badge tone="purple">高频</Badge></span><span><i className="stat-icon orange"><Clock3/></i><b>回答偏长<small>平均 3分12秒 · 建议控制在 2 分钟</small></b><Badge tone="orange">改善中</Badge></span><span><i className="stat-icon blue"><Target/></i><b>量化结果<small>本周覆盖率从 42% 提升至 61%</small></b><Badge tone="green">+19%</Badge></span></div></Card></div></>}

function Questions(){const rows=[["如何保证分布式事务的一致性？","专业知识","5 次","熟悉"],["讲一个解决复杂问题的经历","行为面试","8 次","掌握"],["为什么选择我们公司？","岗位动机","6 次","待加强"],["项目中你最大的个人贡献是什么？","项目深挖","7 次","练习中"],["如何处理团队中的意见冲突？","行为面试","4 次","掌握"]];return <><div className="knowledge-tabs"><button className="active">问题库 <b>126</b></button><button>故事库 <b>18</b></button><button>薄弱项 <b>7</b></button></div><Card className="table-card"><table><thead><tr><th>问题</th><th>类型</th><th>出现次数</th><th>掌握程度</th><th>最近出现</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r[0]}><td><strong>{r[0]}</strong><small>来源：{i%2?"真实面试":"面经 · 模拟面试"}</small></td><td><Badge tone={i%2?"purple":"blue"}>{r[1]}</Badge></td><td>{r[2]}</td><td><span className="mastery"><i style={{width:`${45+i*11}%`}}/></span>{r[3]}</td><td>{i+1} 天前</td></tr>)}</tbody></table></Card></>}

function Offers(){return <><div className="offer-summary"><Card><span className="stat-icon teal"><CircleDollarSign/></span><span><small>已收到 Offer</small><strong>3</strong></span></Card><Card><span className="stat-icon orange"><Clock3/></span><span><small>即将截止</small><strong>1</strong></span></Card><Card><span className="stat-icon blue"><Star/></span><span><small>当前首选</small><strong>蚂蚁集团</strong></span></Card></div><Card className="offer-compare"><CardHeader title="Offer 对比" action="调整权重"/><table><thead><tr><th>比较维度</th><th>权重</th><th>蚂蚁集团</th><th>腾讯科技</th><th>字节跳动</th></tr></thead><tbody>{[["综合得分","—","88","84","82"],["岗位匹配","25%","9.2","8.6","8.4"],["成长空间","20%","9.0","8.5","9.1"],["工作强度","15%","7.2","7.8","6.5"],["城市偏好","15%","9.0","8.0","7.5"],["薪资福利","25%","8.6","8.8","9.0"]].map((r,i)=><tr key={r[0]} className={i===0?"score-row":""}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table><p className="data-disclaimer">评分只根据你设置的权重汇总，最终选择由你决定。</p></Card></>}

function Analytics(){return <><div className="analytics-kpis">{[["总投递","238","本月 +42"],["面试进入率","16.0%","较上月 +2.4%"],["Offer 转化率","2.9%","较上月 +0.6%"],["平均反馈时间","4.2 天","缩短 0.8 天"]].map(([a,b,c])=><Card key={a}><small>{a}</small><strong>{b}</strong><span>{c}</span></Card>)}</div><div className="two-grid analytics-grid"><Card><CardHeader title="近 8 周投递与面试"/><div className="bar-chart">{[42,68,50,78,61,88,72,95].map((h,i)=><div key={i}><span style={{height:`${h}%`}}/><i style={{height:`${h*.42}%`}}/><small>第{i+1}周</small></div>)}</div></Card><Card><CardHeader title="岗位方向分布"/><div className="distribution">{[["后端开发",50.4,120],["数据开发",17.6,42],["人工智能",11.8,28],["产品技术",7.6,18],["其他",12.6,30]].map(([n,p,c])=><div key={n as string}><span>{n}</span><i><b style={{width:`${p}%`}}/></i><strong>{c} <small>({p}%)</small></strong></div>)}</div></Card></div><Card><CardHeader title="行动建议"/><div className="insights"><span><TrendingIcon/><b>内推渠道的面试进入率最高<small>比招聘官网高 8.4 个百分点，可以优先寻找内推机会</small></b></span><span><Target/><b>系统设计题仍是高频薄弱项<small>最近 4 场面试中出现 3 次，建议安排专项训练</small></b></span><span><FileText/><b>“后端开发-2026.07”版本表现更好<small>仅表示统计关联，不代表由简历版本直接造成</small></b></span></div></Card></>}

function SettingsPage(){return <div className="settings-layout"><aside>{[[UserRound,"个人档案"],[BrainCircuit,"AI 服务"],[Mic2,"语音识别"],[Mail,"邮箱连接"],[Database,"数据与备份"],[ShieldCheck,"隐私与安全"],[Settings,"通用设置"]].map(([Icon,label],i)=>{const C=Icon as typeof UserRound;return <button className={i===4?"active":""} key={label as string}><C size={17}/>{label as string}</button>})}</aside><div><Card><CardHeader title="数据与备份"/><div className="setting-block"><div><strong>数据保存位置</strong><p>数据库、简历和面试材料的本地保存目录</p></div><div className="path-field"><code>C:\Users\Lin\AppData\Roaming\TouLeMa</code><button className="button button--secondary">更改位置</button></div></div><div className="setting-block"><div><strong>自动备份</strong><p>定期创建完整数据快照，凭据不会写入备份</p></div><div className="setting-row"><i className="toggle on"/><select><option>每天</option><option>每周</option></select><button className="button button--secondary">立即备份</button></div></div><div className="setting-block"><div><strong>最近备份</strong><p>2026年7月13日 09:20 · 128 MB · 完整性检查通过</p></div><button className="button button--secondary"><RotateCcw size={16}/>恢复备份</button></div></Card><Card><CardHeader title="数据导出"/><div className="setting-block"><div><strong>导出个人数据</strong><p>可导出投递、问题库、面试记录和附件索引</p></div><button className="button button--secondary">创建导出文件</button></div></Card><Card className="danger-zone"><CardHeader title="危险操作"/><div className="setting-block"><div><strong>清空所有数据</strong><p>此操作不可撤销，执行前会要求创建备份并二次确认</p></div><button className="button button--danger">清空数据</button></div></Card></div></div>}

function InfoList({items}:{items:string[][]}){return <div className="info-list">{items.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>}
function CheckList({items}:{items:string[]}){return <div className="check-list">{items.map((x,i)=><button key={x}><i className={i<2?"checked":""}>{i<2&&<Check size={12}/>}</i><span>{x}</span><ChevronRight size={15}/></button>)}</div>}
function SessionList(){return <div className="session-list">{[["快手 · 后端开发二面","昨天 · 48 分钟","转写待校正"],["腾讯 · 技术一面","7月9日 · 56 分钟","复盘完成 60%"],["美团 · HR 面","7月7日 · 32 分钟","待整场总结"]].map((r,i)=><button key={r[0]}><span className="company-logo">{r[0][0]}</span><span><strong>{r[0]}</strong><small>{r[1]}</small></span><Badge tone={i?"purple":"orange"}>{r[2]}</Badge><ChevronRight size={16}/></button>)}</div>}
function TrendingIcon(){return <span className="stat-icon green"><BarChart3/></span>}
