pub(super) const MIGRATIONS: &[(i64, &str, &str)] = &[
    (1, "001_init", include_str!("../../migrations/001_init.sql")),
    (
        2,
        "002_application_detail",
        include_str!("../../migrations/002_application_detail.sql"),
    ),
    (
        3,
        "003_task_notifications",
        include_str!("../../migrations/003_task_notifications.sql"),
    ),
    (
        4,
        "004_provider_settings",
        include_str!("../../migrations/004_provider_settings.sql"),
    ),
    (
        5,
        "005_ai_pipeline",
        include_str!("../../migrations/005_ai_pipeline.sql"),
    ),
    (
        6,
        "006_resume_profiles",
        include_str!("../../migrations/006_resume_profiles.sql"),
    ),
    (
        7,
        "007_resume_workflow",
        include_str!("../../migrations/007_resume_workflow.sql"),
    ),
    (
        8,
        "008_application_event_times",
        include_str!("../../migrations/008_application_event_times.sql"),
    ),
    (
        9,
        "009_application_event_recorded_at",
        include_str!("../../migrations/009_application_event_recorded_at.sql"),
    ),
    (
        10,
        "010_app_settings",
        include_str!("../../migrations/010_app_settings.sql"),
    ),
    (
        11,
        "011_email_pipeline",
        include_str!("../../migrations/011_email_pipeline.sql"),
    ),
    (
        12,
        "012_email_sync_state_repair",
        include_str!("../../migrations/012_email_sync_state_repair.sql"),
    ),
    (
        13,
        "013_email_links",
        include_str!("../../migrations/013_email_links.sql"),
    ),
    (
        14,
        "014_application_stages",
        include_str!("../../migrations/014_application_stages.sql"),
    ),
    (
        15,
        "015_interview_experiences",
        include_str!("../../migrations/015_interview_experiences.sql"),
    ),
    (
        16,
        "016_interview_workflow",
        include_str!("../../migrations/016_interview_workflow.sql"),
    ),
    (
        17,
        "017_email_reliability",
        include_str!("../../migrations/017_email_reliability.sql"),
    ),
];
